/*
Jonan Aney CSD-402 Module M4
Directions:
Write four overloaded methods that return the average of an array with the following headers:

    public static short average (short [ ] array)
    public static int average (int [ ] array)
    public static long average (long [ ] array)
    public static double average (double [ ] array)

Write a test program that invokes each of these methods and then displays the average value returned along with a display of the original array elements. 
Ensure the display is easy to read and understandable. Lastly, each array sent into the methods must be of different sizes to ensure the method code is correctly written.

Sources:
https://www.geeksforgeeks.org/java/method-overloading-in-java/
https://www.w3schools.com/java/java_arrays.asp
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/for.html

* This source file was generated by the Gradle 'init' task
*/

package com.example.j.aney.csd402.mod4;
import java.util.Arrays;

public class App {
// Short method
    public static short average(short[] array) {
        int sum = 0;
        for (short value : array) {
            sum += value;
        }
        return (short) (sum / array.length);
    }
// Int method    
   public static int average(int[] array) {
        int sum = 0;
        for (int value : array) {
            sum += value;
        }
        return sum / array.length;
   }
// Long method   
   public static long average(long[] array) {
        long sum = 0;
        for (long value : array) {
            sum += value;
        }
        return sum / array.length;
    }
// Double method
    public static double average(double[] array) {
        double sum = 0;
        for (double value : array) {
            sum += value;
        }
        return sum / array.length;
    }
    
    public static void main(String[] args) {
// Arrays for testing. All different sizes
        short[] shortArray = {5, 10, 15};
        int[] intArray = {10, 20, 30, 40};
        long[] longArray = {500L, 600L, 700L, 800L, 900L};
        double[] doubleArray = {1.5, 2.5, 3.5, 4.5, 5.5, 6.5};
// Call each method. Display the array vlues and average       
        System.out.println("Short Array: " + Arrays.toString(shortArray));
        System.out.println("Average: " + average(shortArray));
        
        System.out.println("\nInt Array: " + Arrays.toString(intArray));
        System.out.println("Average: " + average(intArray));
        
        System.out.println("\nLong Array: " + Arrays.toString(longArray));
        System.out.println("Average: " + average(longArray));
        
        System.out.println("\nDouble Array: " + Arrays.toString(doubleArray));
        System.out.println("Average: " + average(doubleArray));
    }
        
 }